<?php

return [
    'name'        => 'Alvin Allan Dan Pusta Portfolio',
    'description' => 'Back End Developer & Full-Stack Engineer specializing in PHP, Laravel, Claude AI Subagents, and enterprise systems. 9+ years shipping production software.',

    'requestFramePermissions' => [],
    'majorCapabilities'       => ['MAJOR_CAPABILITY_SERVER_SIDE_GEMINI_API'],

    'featuredSystems' => [
        [
            'id'            => 'pos-multi-terminal',
            'isPersonal'    => true,
            'period'        => 'Independent Project',
            'badge'         => 'Personal Project',
            'badgeClass'    => 'badge-accent',
            'title'         => 'POS & Multi-Terminal System',
            'companyOrType' => 'Personal Portfolio Project',
            'description'   => 'Point-of-sale platform integrated with central inventory for automated real-time sales-to-stock reconciliation and race-condition free multi-terminal synchronization.',
            'tags'          => [
                'Laravel REST API',
                'MySQL Transactions',
                'Terminal Synchronization',
                'Real-Time Stock Audit',
            ],
            'githubUrl'     => 'https://github.com/allanpusta13',
            'galleryUrl'    => '#gallery-pos',
            'screenshots'   => [
                [
                    'title'       => 'POS Cashier Terminal Interface',
                    'caption'     => 'Live item barcode scanning, discount rules, cart calculations, and transaction checkout.',
                    'placeholder' => 'Terminal Register UI',
                ],
                [
                    'title'       => 'Multi-Terminal State Synchronization',
                    'caption'     => 'Real-time stock balance deduction across concurrent point-of-sale registers.',
                    'placeholder' => 'Sync Queue Engine',
                ],
                [
                    'title'       => 'End-of-Day Shift & Audit Reconciliations',
                    'caption'     => 'Automated cash drawer balancing, shift discrepancy auditing, and central inventory updates.',
                    'placeholder' => 'Shift Reconciliation',
                ],
            ],
        ],
        [
            'id'            => 'inventory-management-system',
            'isPersonal'    => true,
            'period'        => 'Independent Project',
            'badge'         => 'Personal Project',
            'badgeClass'    => 'badge-accent',
            'title'         => 'Inventory Management System',
            'companyOrType' => 'Personal Portfolio Project',
            'description'   => 'Full-stack inventory platform featuring built-in branch profiling, real-time stock balance auditing, SKU cataloging, batch & expiration monitoring, and transactional audit logs.',
            'tags'          => [
                'Laravel',
                'Filament Admin',
                'Built-In Branch Profiling',
                'MySQL',
                'Stock Auditing & SKU Tracking',
            ],
            'accentTags'    => [
                'Built-In Branch Profiling',
                'Laravel',
                'Filament Admin',
            ],
            'githubUrl'     => 'https://github.com/allanpusta13',
            'galleryUrl'    => '#gallery-inventory',
            'screenshots'   => [
                [
                    'title'       => 'Central Stock Ledger & SKU Master',
                    'caption'     => 'Multi-category product listings with live inventory counts, unit costs, and reorder levels.',
                    'placeholder' => 'Central Stock Ledger',
                ],
                [
                    'title'       => 'Built-In Branch Profiling & Permits',
                    'caption'     => 'Store branch monitoring module with automated renewal reminders for municipal business permits.',
                    'placeholder' => 'Branch Profiling & Permits',
                ],
                [
                    'title'       => 'Batch & Expiration Tracking',
                    'caption'     => 'FIFO batch routing and critical expiration warnings with automated threshold alerts.',
                    'placeholder' => 'Batch Expiration Monitor',
                ],
            ],
        ],
        [
            'id'            => 'survey-tool',
            'period'        => '04/2023 – 05/2025',
            'badge'         => 'Modernization',
            'badgeClass'    => 'badge-accent',
            'title'         => 'SurveyTool Application',
            'companyOrType' => 'Altern8 Technologies Pte Ltd · Singapore',
            'description'   => 'Enterprise survey assessment and analytics application modernized from legacy PHP 5 to modern PHP 8. Took over and completed the in-progress backend upgrade while modernizing legacy front-end JavaScript features — including upgrading CKEditor rich-text editing, refactoring legacy jQuery modules and AJAX communication layers, optimizing database queries, and executing zero-downtime cutover for uninterrupted respondent workflows.',
            'tags'          => [
                'PHP 5 → PHP 8 Upgrade',
                'CKEditor Upgrade',
                'jQuery Modernization',
                'Legacy JS Refactoring',
                'Zero-Downtime Cutover',
                'MySQL Optimization',
            ],
        ],
        [
            'id'            => 'keyforcare',
            'period'        => '04/2023 – 05/2025',
            'badge'         => 'Healthcare',
            'badgeClass'    => 'badge-accent',
            'title'         => 'KeyForCare Application',
            'companyOrType' => 'Altern8 Technologies Pte Ltd · Singapore',
            'description'   => 'Healthcare service and clinical assessment system modernized from legacy PHP 5 to secure PHP 8. Stepped into the ongoing upgrade process, upgrading client-side JavaScript features including CKEditor and jQuery integrations, refactoring deprecated database drivers, hardening session security, and ensuring zero service disruption.',
            'tags'          => [
                'PHP 5 → PHP 8 Upgrade',
                'CKEditor Upgrade',
                'jQuery Modernization',
                'Healthcare Assessment',
                'Zero-Downtime Cutover',
                'Security Hardening',
            ],
        ],
        [
            'id'            => 'ats',
            'period'        => '04/2023 – 05/2025',
            'badge'         => 'Laravel & Filament',
            'badgeClass'    => 'badge-accent',
            'title'         => 'Applicant Tracking System',
            'companyOrType' => 'Altern8 Technologies Pte Ltd · Singapore',
            'description'   => 'Candidate pipeline management platform built from Laravel and Filament, featuring granular role-based permissions (RBAC), customizable recruitment stage transitions, and automated notification workflows.',
            'tags'          => [
                'Laravel',
                'Filament Admin',
                'RBAC Security',
                'Workflow Automation',
            ],
            'accentTags'    => [
                'Laravel',
                'Filament Admin',
            ],
        ],
        [
            'id'            => 'comaea',
            'period'        => '04/2023 – 05/2025',
            'badge'         => 'Consulting Suite',
            'badgeClass'    => 'badge-accent',
            'title'         => 'Comaea Consulting Platform',
            'companyOrType' => 'Altern8 Technologies Pte Ltd · Singapore',
            'description'   => 'Consulting analytics suite supporting complex survey assessment logic, multi-tier corporate client administration, recurring billing subscriptions, and visual report generation.',
            'tags'          => [
                'Laravel + React.js',
                'Survey Engine',
                'Subscription Billing',
                'Export Pipelines',
            ],
        ],
        [
            'id'            => 'booking-engine-api',
            'period'        => '06/2022 – 05/2023',
            'badge'         => 'Featured API',
            'badgeClass'    => 'badge-accent',
            'title'         => 'Booking Engine Application (API)',
            'companyOrType' => 'Adaca · Australia',
            'description'   => 'Central high-throughput Back-End API managing multi-service appointment scheduling for Pet Grooming and Veterinary clinics. Serves as the authoritative source of truth for customer and pet profiles, appointment status lifecycles, and calendar slot availability across approximately 5 connected front-end applications.',
            'tags'          => [
                'Laravel REST API',
                '5 Front-End Clients',
                'Customer & Pet Data',
                'Slot Availability Logic',
                'MySQL / PostgreSQL',
            ],
        ],
        [
            'id'            => 'grooming-microsite',
            'period'        => '06/2022 – 05/2023',
            'badge'         => 'Featured Portal',
            'badgeClass'    => 'badge-accent',
            'title'         => 'Grooming Booking Microsite',
            'companyOrType' => 'Adaca · Australia',
            'description'   => 'Dedicated customer-facing front-end web portal engineered for pet grooming reservations. Provides an intuitive, responsive booking journey for both first-time and returning users, featuring live groomer schedule viewing, pet size and grooming service package selection, and instant confirmation dispatch via the central Booking Engine API.',
            'tags'          => [
                'Front-End Web Portal',
                'New & Returning Users',
                'Grooming Package Config',
                'Live Calendar Booking',
                'API Integration',
            ],
        ],
        [
            'id'            => 'vet-microsite',
            'period'        => '06/2022 – 05/2023',
            'badge'         => 'Featured Portal',
            'badgeClass'    => 'badge-accent',
            'title'         => 'Vet Booking Microsite',
            'companyOrType' => 'Adaca · Australia',
            'description'   => 'Specialized clinical appointment front-end portal built for veterinary consultations and animal health services. Enables seamless client intake for both new patients and registered pet owners, doctor schedule matching, appointment reason categorization, and real-time synchronization with veterinary clinic rosters.',
            'tags'          => [
                'Front-End Web Portal',
                'Veterinary Intake Portal',
                'Clinician Schedule Match',
                'New & Returning Pet Owners',
                'Booking Engine API',
            ],
        ],
        [
            'id'            => 'multi-branch-inventory',
            'period'        => '12/2017 – 01/2023',
            'badge'         => 'Vanilla PHP 5',
            'badgeClass'    => 'badge-accent',
            'title'         => 'Multi-Branch Inventory System',
            'companyOrType' => 'Yamang Bukid Healthy · Baguio City, PH',
            'description'   => 'Multi-company inventory management architecture built in pure vanilla PHP 5 (no framework), supporting inter-branch stock routing, transfers, low-stock threshold triggers, and central warehouse reporting.',
            'tags'          => [
                'Pure Vanilla PHP 5',
                'No Framework',
                'MySQL',
                'Multi-Branch Routing',
                'Stock Transfer Engine',
            ],
        ],
        [
            'id'            => 'branch-profiling',
            'period'        => '12/2017 – 01/2023',
            'badge'         => 'Laravel & Filament',
            'badgeClass'    => 'badge-accent',
            'title'         => 'Branch Profiling System',
            'companyOrType' => 'Yamang Bukid Healthy · Baguio City, PH',
            'description'   => 'Developed using Laravel and Filament to monitor and track the validity of business permits across all company branches, keeping regulatory documents up to date with automated reminder schedules dispatched to administrators for timely renewals.',
            'tags'          => [
                'Laravel',
                'Filament Admin',
                'Business Permit Monitoring',
                'Renewal Reminders',
                'Compliance Automation',
                'Admin Notifications',
            ],
            'accentTags'    => [
                'Laravel',
                'Filament Admin',
            ],
        ],
        [
            'id'            => 'hris',
            'period'        => '12/2017 – 01/2023',
            'badge'         => 'Custom Core',
            'badgeClass'    => 'badge-accent',
            'title'         => 'HRIS & Workforce Platform',
            'companyOrType' => 'Yamang Bukid Healthy · Baguio City, PH',
            'description'   => 'Engineered HRIS from scratch (initial custom PHP with no framework), scaling across company branches with automated attendance calculation, employee profiling, and payroll data integration.',
            'tags'          => [
                'PHP (No Framework)',
                'AJAX / jQuery',
                'MySQL',
                'Attendance & Payroll',
            ],
        ],
    ],

    'techStack' => [
        [
            'id'         => 'ai-agentic',
            'category'   => 'AI & Agentic Engineering',
            'badge'      => 'LinkedIn Top Skills',
            'isWide'     => true,
            'isFeatured' => true,
            'skills'     => [
                ['name' => 'Claude Code Subagents', 'accent' => true],
                ['name' => 'Anthropic Claude',      'accent' => true],
                ['name' => 'Claude Skills',         'accent' => true],
                ['name' => 'Claude 101 Certified',  'accent' => false],
                ['name' => 'Claude Code 101 Certified', 'accent' => false],
                ['name' => 'AI-Assisted Workflow Automation', 'accent' => false],
            ],
        ],
        [
            'id'       => 'backend',
            'category' => 'Backend & Frameworks',
            'isWide'   => true,
            'skills'   => [
                ['name' => 'PHP 8.x', 'accent' => true],
                ['name' => 'Laravel (10 / 11)', 'accent' => true],
                ['name' => 'Filament 3.x', 'accent' => true],
                ['name' => 'Livewire 3.x', 'accent' => true],
                ['name' => 'PHP 5.x → 8.x Modernization', 'accent' => false],
                ['name' => 'Composer', 'accent' => false],
                ['name' => 'Eloquent ORM', 'accent' => false],
            ],
        ],
        [
            'id'       => 'frontend',
            'category' => 'Frontend & UI',
            'isWide'   => false,
            'skills'   => [
                ['name' => 'Alpine.js'],
                ['name' => 'Tailwind CSS'],
                ['name' => 'React.js'],
                ['name' => 'TypeScript'],
                ['name' => 'JavaScript (ES6+)'],
                ['name' => 'jQuery'],
                ['name' => 'Bootstrap'],
                ['name' => 'AJAX'],
            ],
        ],
        [
            'id'       => 'databases',
            'category' => 'Databases & Storage',
            'isWide'   => false,
            'skills'   => [
                ['name' => 'MySQL'],
                ['name' => 'PostgreSQL'],
                ['name' => 'SQLite'],
                ['name' => 'Database Migrations'],
                ['name' => 'Indexing & Optimization'],
            ],
        ],
        [
            'id'       => 'devops',
            'category' => 'Architecture, DevOps & Tooling',
            'isWide'   => true,
            'skills'   => [
                ['name' => 'RESTful API Design'],
                ['name' => 'Zero-Downtime Migration'],
                ['name' => 'Git & GitHub'],
                ['name' => 'CI/CD Pipelines'],
                ['name' => 'Windows Server'],
                ['name' => 'AWS Cloud Services'],
                ['name' => 'Automated Testing (Playwright / PHPUnit)'],
            ],
        ],
        [
            'id'       => 'systems-infra',
            'category' => 'Systems, Hardware & Infrastructure',
            'isWide'   => true,
            'isSubtle' => true,
            'skills'   => [
                ['name' => 'CCTV Setup & Management'],
                ['name' => 'Network Micromanagement & LAN'],
                ['name' => 'PC Building & Troubleshooting'],
                ['name' => 'Telephone Systems / PABX'],
                ['name' => 'POS Terminal Configuration'],
                ['name' => 'Thermal Printer Maintenance'],
                ['name' => 'Fire Alarm Systems'],
                ['name' => 'Theater & AV Setup'],
                ['name' => 'Graphic Designs (Posters & Print)'],
            ],
        ],
    ],

    'experience' => [
        [
            'id'       => 'eizcee',
            'current'  => true,
            'period'   => '05/2025 – Present',
            'duration' => null,
            'role'     => 'Cashier',
            'company'  => 'Eizcee Food Corner',
            'location' => null,
            'bullets'  => [
                'Handle sales transactions, cash reconciliation, and daily bookkeeping',
                'Support inventory tracking and vendor coordination',
            ],
        ],
        [
            'id'       => 'altern8',
            'current'  => false,
            'period'   => '04/2023 – 05/2025',
            'duration' => '2 yrs 2 mos',
            'role'     => 'Back End Developer',
            'company'  => 'Altern8 Technologies Pte Ltd',
            'location' => 'Singapore',
            'bullets'  => [
                '<strong>SurveyTool Application:</strong> Took over and completed the in-progress legacy upgrade from PHP 5 to modern PHP 8, alongside upgrading frontend JavaScript tooling (CKEditor rich-text features, jQuery, AJAX communication), resolving deprecated functions, optimizing database queries, and executing zero-downtime cutover for continuous respondent workflows',
                '<strong>KeyForCare Application:</strong> Stepped into the ongoing upgrade process transitioning the healthcare assessment platform from legacy PHP 5 to modern PHP 8, updating client-side JavaScript components (CKEditor, jQuery), resolving deprecated dependencies, fortifying session security, and ensuring zero service disruption',
                '<strong>Comaea Consulting Platform:</strong> Architected consulting analytics suite and multi-tenant survey assessment web systems using Laravel and React',
                '<strong>Applicant Tracking System (ATS):</strong> Built recruitment management application using Laravel and Filament, featuring granular role-based access control (RBAC), customizable pipeline stages, and automated notification workflows',
            ],
        ],
        [
            'id'       => 'adaca',
            'current'  => false,
            'period'   => '06/2022 – 05/2023',
            'duration' => '1 yr',
            'role'     => 'Full Stack Laravel Application Developer',
            'company'  => 'Adaca',
            'location' => 'Australia',
            'bullets'  => [
                '<strong>Booking Engine Application:</strong> Architected centralized Back-End API managing appointments for Pet Grooming and Vet clinics; served as the single source of truth for customer/pet data and live scheduling across ~5 front-end applications',
                '<strong>Grooming Microsite:</strong> Built dedicated client-facing front-end portal enabling streamlined pet grooming bookings, live groomer calendar selection, and custom service packages for new and returning users',
                '<strong>Vet Microsite:</strong> Engineered specialized veterinary consultation booking portal handling patient intake, triage categorization, and doctor roster synchronization for both new and registered clients',
                'Collaborated closely with product managers and QA engineers to triage edge cases, ensure cross-system data consistency, and execute stable production releases',
            ],
        ],
        [
            'id'       => 'yamang-bukid',
            'current'  => false,
            'period'   => '12/2017 – 01/2023',
            'duration' => '5 yrs 2 mos',
            'role'     => 'Management Information System Officer',
            'company'  => 'Yamang Bukid Healthy',
            'location' => 'Baguio City, Cordillera Admin Region, Philippines',
            'bullets'  => [
                '<strong>Full Stack Systems Development:</strong> Built and shipped internal platforms for HRIS, Multi-Branch Inventory, and Branch Profiling using PHP, Filament, AJAX, jQuery, Bootstrap, Tailwind, Laravel Framework, Git, and MySQL',
                '<strong>HRIS Platform:</strong> Engineered workforce platform from scratch with no framework, handling attendance calculations, payroll logic, and employee profiling',
                '<strong>Multi-Branch Inventory System:</strong> Developed in pure vanilla PHP 5 (no framework), supporting multi-company stock routing, transfers, and low-stock threshold triggers',
                '<strong>Branch Profiling System:</strong> Engineered using Laravel and Filament to monitor the validity of business permits across all operating branches, providing automated reminders and alert schedules to administrators for timely renewals',
                '<strong>IT Infrastructure & Hardware:</strong> Managed CCTV setup & maintenance, network micromanagement, PC building for company needs, and computer hardware troubleshooting',
            ],
        ],
        [
            'id'       => 'garden-orchid',
            'current'  => false,
            'period'   => '02/2016 – 10/2017',
            'duration' => '1 yr 9 mos',
            'role'     => 'Information Technology Specialist',
            'company'  => 'Garden Orchid Hotel',
            'location' => 'Zamboanga, Zamboanga Peninsula, Philippines',
            'bullets'  => [
                'Setup, configured, and managed CCTV surveillance and telecommunications (telephone / PABX) across hotel premises',
                'PC troubleshooting, hardware diagnostics, and thermal/POS printer maintenance',
                'Fire alarm setup and management ensuring municipal life-safety and hospitality compliance',
                'Network micromanagement for high-density guest Wi-Fi and administrative LAN networks',
                'Graphic designs for promotional posters, marketing collaterals, and theater audiovisual event setups',
            ],
        ],
    ],

    'competencies' => [
        'focusAreas' => [
            [
                'id'          => 'legacy-modernization',
                'title'       => 'Legacy Modernization & Refactoring',
                'description' => 'Deep specialization in safely migrating mission-critical legacy PHP 5.x codebases to modern PHP 8.x and current Laravel versions. Focus on zero-downtime releases, preserving historical data integrity, and replacing deprecated extensions with modern ORM patterns.',
                'isWide'      => true,
                'tags'        => [
                    'PHP5 → PHP8 Migration',
                    'Zero-Downtime Cutover',
                    'Data Schema Migration',
                    'Performance Profiling',
                ],
            ],
            [
                'id'          => 'enterprise-architecture',
                'title'       => 'Enterprise Systems Architecture',
                'description' => 'Designing multi-branch inventory platforms, HRIS suites, and automated applicant tracking systems with granular role-based access control (RBAC) and automated workflow triggers.',
                'isWide'      => false,
                'tags'        => [
                    'Multi-Branch Sync',
                    'RBAC Security',
                    'Automated Workflows',
                ],
            ],
            [
                'id'          => 'operational-acumen',
                'title'       => 'Operational & Systems Acumen',
                'description' => 'Hands-on background bridging software engineering with physical business workflows: POS terminal synchronization, real-time inventory deductions, and hardware networking reliability.',
                'isWide'      => false,
                'tags'        => [
                    'POS & Inventory Logic',
                    'Audit & Reconciliation',
                    'Network Reliability',
                ],
            ],
        ],

        'educationAndCertifications' => [
            'isWide'   => true,
            'category' => 'Education, Certifications & AI Specialization',
            'education' => [
                'degree'      => 'BS in Computer Engineering',
                'institution' => 'Western Mindanao State University',
                'period'      => '2009 – 2016',
                'description' => 'Strong academic and practical engineering foundation in digital computer systems, architecture, networking, and applied software programming.',
                'tags'        => [
                    'Computer Engineering',
                    'Digital Systems',
                    'Networks',
                ],
            ],
            'certifications' => [
                'title'    => 'Anthropic Claude Certifications',
                'subtitle' => 'Verified Certificates of Completion',
                'certs'    => [
                    'Certificate of Completion: Claude 101',
                    'Certificate of Completion: Claude Code 101',
                ],
                'topSkillsLabel' => 'LinkedIn Top Skills:',
                'topSkills'      => [
                    ['name' => 'Claude Code Subagents', 'accent' => true],
                    ['name' => 'Anthropic Claude',      'accent' => false],
                    ['name' => 'Claude Skills',         'accent' => false],
                ],
            ],
        ],
    ],
];